In [ ]:

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]  # CreditPathAI_Oct_Batch
sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)



from src.utils import print_tree
print_tree(PROJECT_ROOT  , depth=1)

Project root: d:\projects\CreditPathAI_Oct_Batch
CreditPathAI_Oct_Batch/
    .git/
        COMMIT_EDITMSG
        config
        description
        FETCH_HEAD
        HEAD
        index
        ORIG_HEAD
        packed-refs
    .gitattributes
    .gitignore
    .venv/
        .gitignore
        pyvenv.cfg
    artifacts/
    CreditPathAI_Oct_Batch/
    git
    kaggle_dataset/
        .gitignore
        README.md
        requirements.txt
    LICENSE
    main.py
    microsoft_dataset/
        microsoft_main.ipynb
    README.md
    requirements.txt
    src/
        eda.py
        evaluate.py
        inference.py
        ingestion.py
        models.py
        preprocess.py
        utils.py
        __init__.py
    streamlit/
        streamlit_app.py

In [4]:
import pandas as pd

borrower_path = PROJECT_ROOT / "microsoft_dataset" / "data" / "raw" / "Borrower.txt"
df_borrower = pd.read_csv(borrower_path, sep="\t")

print('borrower shape : ',df_borrower.shape)
df_borrower.head()

borrower shape :  (100000, 17)

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1

In [5]:
loan_path = PROJECT_ROOT / "microsoft_dataset" / "data" / "raw" / "Loan.txt"
df_loan = pd.read_csv(loan_path, sep="\t")

print('loan shape : ',df_loan.shape)
df_loan.head()

loan shape :  (100000, 11)

,loanId,memberId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus
0,1888978,2305095,12/10/2014,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current
1,1299695,2610493,9/15/2014,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current
2,1875016,2491679,9/11/2014,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current
3,1440478,2092798,4/22/2016,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current
4,1124634,2633077,2/3/2016,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current

In [ ]:
df = pd.merge(df_borrower, df_loan, on='memberId', how='inner')

print("Merged DataFrame (first 5 rows):")
display(df.head())

print("\nMerged DataFrame Info:")
df.info()

print("\nShape of the merged DataFrame:")
print(df.shape)

Merged DataFrame (first 5 rows):

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,...,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,...,1888978,12/10/2014,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,...,1299695,9/15/2014,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,...,1875016,9/11/2014,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,...,1440478,4/22/2016,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,...,1124634,2/3/2016,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current

Merged DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   memberId                  100000 non-null  int64
 1   residentialState          100000 non-null  object
 2   yearsEmployment           100000 non-null  object
 3   homeOwnership             100000 non-null  object
 4   annualIncome              100000 non-null  int64
 5   incomeVerified            100000 non-null  int64
 6   dtiRatio                  100000 non-null  float64
 7   lengthCreditHistory       100000 non-null  int64
 8   numTotalCreditLines       100000 non-null  int64
 9   numOpenCreditLines        99033 non-null   float64
 10  numOpenCreditLines1Year   100000 non-null  int64
 11  revolvingBalance          100000 non-null  int64
 12  revolvingUtilizationRate  100000 non-null  float64
 13  numDerogatoryRec          100000 non-null  int64
 14  numDelinquency2Years      100000 non-null  int64
 15  numChargeoff1year         100000 non-null  int64
 16  numInquiries6Mon          100000 non-null  int64
 17  loanId                    100000 non-null  int64
 18  date                      100000 non-null  object
 19  purpose                   100000 non-null  object
 20  isJointApplication        99029 non-null   float64
 21  loanAmount                98994 non-null   float64
 22  term                      98929 non-null   object
 23  interestRate              100000 non-null  float64
 24  monthlyPayment            100000 non-null  int64
 25  grade                     100000 non-null  object
 26  loanStatus                100000 non-null  object
dtypes: float64(6), int64(13), object(8)
memory usage: 20.6+ MB

Shape of the merged DataFrame:
(100000, 27)

In [7]:
df['loanStatus'].value_counts()

loanStatus
Current    89996
Default    10004
Name: count, dtype: int64

In [8]:
df['defaultFlag'] = df['loanStatus'].map({
    'Current': 0,
    'Default': 1
})

print(df['defaultFlag'].value_counts())
df[['loanStatus', 'defaultFlag']].head()

defaultFlag
0    89996
1    10004
Name: count, dtype: int64

  loanStatus  defaultFlag
0    Current            0
1    Current            0
2    Current            0
3    Current            0
4    Current            0

In [9]:
df.to_csv(PROJECT_ROOT / "microsoft_dataset" / "data" / "interim" / "merged_loan_borrower.csv", index=False)