In [49]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
assert (PROJECT_ROOT / "src").exists(), "src NOT FOUND — WRONG ROOT"

sys.path.insert(0, str(PROJECT_ROOT))

print(" Project root added:", PROJECT_ROOT)


import pandas as pd

from src.preprocess import *

 Project root added: d:\projects\CreditPathAI_Oct_Batch

In [72]:

data_path = PROJECT_ROOT /"microsoft_dataset"/"data"/"interim"/"merged_loan_borrower.csv"
preprocessed_path = PROJECT_ROOT /"microsoft_dataset/data/processed/merged_loan_preprocessed.csv"
df = pd.read_csv(data_path)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Missing values:\n", df.isnull().sum()[df.isnull().sum() > 0])
print("Duplicate rows:", df.duplicated().sum())

Shape: (100000, 28)
Columns: ['memberId', 'residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome', 'incomeVerified', 'dtiRatio', 'lengthCreditHistory', 'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year', 'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec', 'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon', 'loanId', 'date', 'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate', 'monthlyPayment', 'grade', 'loanStatus', 'defaultFlag']
Missing values:
 numOpenCreditLines     967
isJointApplication     971
loanAmount            1006
term                  1071
dtype: int64
Duplicate rows: 0

In [73]:
cols_to_drop = [col for col in df.columns if df[col].isnull().sum() == len(df)]
df.drop(columns=cols_to_drop, inplace=True)
print("Dropped Columns:", cols_to_drop)

Dropped Columns: []

In [74]:
df.head()

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus,defaultFlag
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0,1888978,12/10/2014,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current,0
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0,1299695,9/15/2014,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current,0
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0,1875016,9/11/2014,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current,0
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3,1440478,4/22/2016,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current,0
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1,1124634,2/3/2016,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current,0

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   memberId                  100000 non-null  int64
 1   residentialState          100000 non-null  object
 2   yearsEmployment           100000 non-null  object
 3   homeOwnership             100000 non-null  object
 4   annualIncome              100000 non-null  int64
 5   incomeVerified            100000 non-null  int64
 6   dtiRatio                  100000 non-null  float64
 7   lengthCreditHistory       100000 non-null  int64
 8   numTotalCreditLines       100000 non-null  int64
 9   numOpenCreditLines        99033 non-null   float64
 10  numOpenCreditLines1Year   100000 non-null  int64
 11  revolvingBalance          100000 non-null  int64
 12  revolvingUtilizationRate  100000 non-null  float64
 13  numDerogatoryRec          100000 non-null  int64
 14  numDelinquency2Years      100000 non-null  int64
 15  numChargeoff1year         100000 non-null  int64
 16  numInquiries6Mon          100000 non-null  int64
 17  loanId                    100000 non-null  int64
 18  date                      100000 non-null  object
 19  purpose                   100000 non-null  object
 20  isJointApplication        99029 non-null   float64
 21  loanAmount                98994 non-null   float64
 22  term                      98929 non-null   object
 23  interestRate              100000 non-null  float64
 24  monthlyPayment            100000 non-null  int64
 25  grade                     100000 non-null  object
 26  loanStatus                100000 non-null  object
 27  defaultFlag               100000 non-null  int64
dtypes: float64(6), int64(14), object(8)
memory usage: 21.4+ MB

In [76]:
print("Columns:", df.columns.tolist())
print("Shape",df.shape)

Columns: ['memberId', 'residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome', 'incomeVerified', 'dtiRatio', 'lengthCreditHistory', 'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year', 'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec', 'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon', 'loanId', 'date', 'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate', 'monthlyPayment', 'grade', 'loanStatus', 'defaultFlag']
Shape (100000, 28)

In [77]:


# GENERIC PROCESSING
df = handle_missing_values(df)
df = parse_datetime_columns(df,datetime_cols=["date"])
#df = one_hot_encode(df)
#df = handle_outliers_iqr(df, method="cap")
#df, scaler = scale_features(df, method="standard")

Parsed datetime column 'date' into 'date_year' and 'date_month'. and if u want u can drop the original column as well

In [78]:
df.head(10)

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus,defaultFlag,date_year,date_month,date_day
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0,1888978,2014-12-10,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current,0,2014,12,10
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0,1299695,2014-09-15,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current,0,2014,9,15
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0,1875016,2014-09-11,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current,0,2014,9,11
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3,1440478,2016-04-22,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current,0,2016,4,22
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1,1124634,2016-02-03,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current,0,2016,2,3
5,2385245,NH,2-5 years,rent,58459,0,15.77,1,18,15.0,8,18830,59.61,0,0,0,0,1697652,2015-11-14,debtconsolidation,0.0,17905.0,60 months,10.43,384,A1,Current,0,2015,11,14
6,2796457,VT,6-9 years,rent,56611,0,13.52,1,9,7.0,5,17157,43.01,0,0,0,0,1050350,2014-05-14,debtconsolidation,0.0,26238.0,36 months,10.96,859,B3,Current,0,2014,5,14
7,2822245,CA,10+ years,mortgage,58163,0,25.22,6,14,9.0,5,15867,62.55,0,0,0,0,1278582,2015-04-08,healthcare,0.0,21940.0,48 months,10.28,559,B1,Current,0,2015,4,8
8,2462353,IN,10+ years,rent,55636,1,9.97,10,19,12.0,5,12908,67.67,0,20,15,1,1245174,2014-10-22,debtconsolidation,0.0,18195.0,36 months,12.08,605,A1,Current,0,2014,10,22
9,2404666,IL,6-9 years,mortgage,54599,0,20.90,26,16,11.0,10,15235,58.07,1,0,0,1,1127834,2015-12-12,debtconsolidation,0.0,24418.0,48 months,11.63,639,B1,Current,0,2015,12,12

In [79]:
df=df.drop(columns=['date_day'])

In [80]:

print("Columns:", df.columns.tolist())
print("Shape",df.shape)
df.head(10)

Columns: ['memberId', 'residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome', 'incomeVerified', 'dtiRatio', 'lengthCreditHistory', 'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year', 'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec', 'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon', 'loanId', 'date', 'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate', 'monthlyPayment', 'grade', 'loanStatus', 'defaultFlag', 'date_year', 'date_month']
Shape (100000, 30)

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus,defaultFlag,date_year,date_month
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0,1888978,2014-12-10,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current,0,2014,12
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0,1299695,2014-09-15,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current,0,2014,9
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0,1875016,2014-09-11,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current,0,2014,9
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3,1440478,2016-04-22,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current,0,2016,4
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1,1124634,2016-02-03,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current,0,2016,2
5,2385245,NH,2-5 years,rent,58459,0,15.77,1,18,15.0,8,18830,59.61,0,0,0,0,1697652,2015-11-14,debtconsolidation,0.0,17905.0,60 months,10.43,384,A1,Current,0,2015,11
6,2796457,VT,6-9 years,rent,56611,0,13.52,1,9,7.0,5,17157,43.01,0,0,0,0,1050350,2014-05-14,debtconsolidation,0.0,26238.0,36 months,10.96,859,B3,Current,0,2014,5
7,2822245,CA,10+ years,mortgage,58163,0,25.22,6,14,9.0,5,15867,62.55,0,0,0,0,1278582,2015-04-08,healthcare,0.0,21940.0,48 months,10.28,559,B1,Current,0,2015,4
8,2462353,IN,10+ years,rent,55636,1,9.97,10,19,12.0,5,12908,67.67,0,20,15,1,1245174,2014-10-22,debtconsolidation,0.0,18195.0,36 months,12.08,605,A1,Current,0,2014,10
9,2404666,IL,6-9 years,mortgage,54599,0,20.90,26,16,11.0,10,15235,58.07,1,0,0,1,1127834,2015-12-12,debtconsolidation,0.0,24418.0,48 months,11.63,639,B1,Current,0,2015,12

In [81]:
df = label_encode(df,columns=['residentialState', 'yearsEmployment', 'homeOwnership',
            'purpose', 'term', 'grade'])
print("Columns:", df.columns.tolist())
print("Shape",df.shape)
df.head(10)

Columns: ['memberId', 'residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome', 'incomeVerified', 'dtiRatio', 'lengthCreditHistory', 'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year', 'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec', 'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon', 'loanId', 'date', 'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate', 'monthlyPayment', 'grade', 'loanStatus', 'defaultFlag', 'date_year', 'date_month']
Shape (100000, 30)

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus,defaultFlag,date_year,date_month
0,2305095,30,1,2,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0,1888978,2014-12-10,2,0.0,25190.0,2,6.25,490,14,Current,0,2014,12
1,2610493,45,2,2,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0,1299695,2014-09-15,2,0.0,21189.0,2,10.49,455,5,Current,0,2014,9
2,2491679,23,4,2,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0,1875016,2014-09-11,2,0.0,29908.0,2,9.11,622,4,Current,0,2014,9
3,2092798,41,3,1,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3,1440478,2016-04-22,5,0.0,13053.0,1,11.89,343,5,Current,0,2016,4
4,2633077,17,2,2,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1,1124634,2016-02-03,2,0.0,24613.0,2,15.13,587,2,Current,0,2016,2
5,2385245,28,2,2,58459,0,15.77,1,18,15.0,8,18830,59.61,0,0,0,0,1697652,2015-11-14,2,0.0,17905.0,2,10.43,384,0,Current,0,2015,11
6,2796457,44,3,2,56611,0,13.52,1,9,7.0,5,17157,43.01,0,0,0,0,1050350,2014-05-14,2,0.0,26238.0,0,10.96,859,5,Current,0,2014,5
7,2822245,3,1,0,58163,0,25.22,6,14,9.0,5,15867,62.55,0,0,0,0,1278582,2015-04-08,4,0.0,21940.0,1,10.28,559,3,Current,0,2015,4
8,2462353,13,1,2,55636,1,9.97,10,19,12.0,5,12908,67.67,0,20,15,1,1245174,2014-10-22,2,0.0,18195.0,0,12.08,605,0,Current,0,2014,10
9,2404666,12,3,0,54599,0,20.90,26,16,11.0,10,15235,58.07,1,0,0,1,1127834,2015-12-12,2,0.0,24418.0,1,11.63,639,3,Current,0,2015,12

In [60]:
convert_floats_to_float32(df)
downcast_integers(df)

Downcasting 6 float64 columns to float32.
Downcasting 20 int64 columns to smaller integer types.

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,...,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus,defaultFlag,date_year,date_month
0,2305095,30,1,2,56471,1,16.799999,6,11,9.0,...,0.0,25190.0,2,6.25,490,14,Current,0,2014,12
1,2610493,45,2,2,55038,0,19.990000,22,8,7.0,...,0.0,21189.0,2,10.49,455,5,Current,0,2014,9
2,2491679,23,4,2,56610,1,14.330000,5,8,5.0,...,0.0,29908.0,2,9.11,622,4,Current,0,2014,9
3,2092798,41,3,1,54887,1,14.800000,12,14,7.0,...,0.0,13053.0,1,11.89,343,5,Current,0,2016,4
4,2633077,17,2,2,53522,1,10.140000,4,21,19.0,...,0.0,24613.0,2,15.13,587,2,Current,0,2016,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2069462,16,2,1,58987,0,21.620001,2,16,10.0,...,0.0,25874.0,2,10.95,562,1,Current,0,2016,5
99996,2218175,22,3,2,54245,1,15.600000,11,11,7.0,...,0.0,18557.0,2,5.31,353,0,Current,0,2015,6
99997,2262127,7,0,2,54923,0,13.960000,2,21,13.0,...,0.0,15877.0,0,9.87,511,1,Current,0,2014,11
99998,2501174,3,0,1,57809,1,9.070000,36,18,12.0,...,0.0,15601.0,2,7.31,311,8,Current,0,2015,6
99999,2134068,21,3,2,52150,1,11.350000,6,13,13.0,...,0.0,20500.0,1,12.98,550,1,Current,0,2015,8

In [82]:
df=df.drop(columns=['date'])

In [83]:
target_col = 'loanStatus'

X = df.drop(columns=[target_col])
y = df[target_col]

In [84]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [85]:
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns,
    index=X.index
)

df_processed = pd.concat([X_scaled, y], axis=1)

In [86]:
# Save the preprocessed data
df.to_csv(preprocessed_path, index=False)
print("Preprocessed data saved to:", preprocessed_path)

Preprocessed data saved to: d:\projects\CreditPathAI_Oct_Batch\microsoft_dataset\data\processed\merged_loan_preprocessed.csv

In [87]:
assert y.nunique() == 2